### ISSUE TITLE
Server data directory "/share" is invalid or doesn't exits

### ISSUE THREAD

**Issue by lorenzschmid** [haiwen/seafile-docker#100]
I followed the "Getting Started" section of the README where it is stated to mount an external volume with the following attribute `-v /opt/seafile-data:/shared` (not the "d" at the end of `/shared`). Unfortunately, when I want to start up my container it only comes up briefly before restarting. It seems as if it is missing the path `/share`(without a "d" at the end):

```
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep  5 06:38:42 3b98d4bb37c5 syslog-ng[30]: syslog-ng starting up; version='3.5.6'
Sep  5 06:38:42 3b98d4bb37c5 syslog-ng[30]: EOF on control channel, closing connection;
*** Running /etc/my_init.d/99_mysql_setup.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 37
*** Running /scripts/start.py...
Sep  5 06:38:42 3b98d4bb37c5 cron[45]: (CRON) INFO (pidfile fd = 3)
Sep  5 06:38:42 3b98d4bb37c5 cron[45]: (CRON) INFO (Running @reboot jobs)
[2018-09-05 06:38:45] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.

Your seafile server data directory "/share" is invalid or doesn't exits.
Please check it first, or create this directory yourself.

Traceback (most recent call last):
  File "/scripts/start.py", line 85, in <module>
    main()
  File "/scripts/start.py", line 71, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.2/seafile.sh start' returned non-zero exit status 1
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 37)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Sep  5 06:38:49 3b98d4bb37c5 syslog-ng[30]: syslog-ng shutting down; version='3.5.6'
Sep  5 06:38:49 3b98d4bb37c5 syslog-ng[30]: EOF on control channel, closing connection;
*** Killing all processes...
```

**Comment by lorenzschmid** [comment]
Adding `/share` (without a "d" at the end) as volume pointing on the same location as `/shared` (`-v /opt/seafile-data:/shared -v /opt/seafile-data:/share`) results in a different issue #101.

**Comment by lorenzschmid** [comment]
My bad: I transfered an old installation and forgot to change the library's path in the `ccnet/seafile.ini` file.
