### ISSUE TITLE
Mounting /etc/localtime prevents start up

### ISSUE THREAD

**Issue by lorenzschmid** [haiwen/seafile-docker#101]
After having followed the "Getting Started" section of the README and imported an existing seafile installation (see the manual for backup and restore) my container never wants to come up and is constantly restarting. It seems like seahub cannot start - unfortunately without any further indication why not:

```
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Sep  5 04:36:13 a7574958f39a syslog-ng[29]: syslog-ng starting up; version='3.5.6'
Sep  5 04:36:14 a7574958f39a syslog-ng[29]: EOF on control channel, closing connection;
*** Running /etc/my_init.d/99_mysql_setup.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 36
*** Running /scripts/start.py...
Sep  5 04:36:14 a7574958f39a cron[44]: (CRON) INFO (pidfile fd = 3)
Sep  5 04:36:14 a7574958f39a cron[44]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
[2018-09-05 04:36:16] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.

[09/05/18 04:36:16] ../common/session.c(132): using config file /opt/seafile/conf/ccnet.conf
Starting seafile server, please wait ...
Seafile server started

Done.

Starting seahub at port 8000 ...
Error:Seahub failed to start.
Please try to run "./seahub.sh start" again
Traceback (most recent call last):
  File "/scripts/start.py", line 85, in <module>
    main()
  File "/scripts/start.py", line 72, in main
    call('{} start'.format(get_script('seahub.sh')))
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.2/seahub.sh start' returned non-zero exit status 1
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 36)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Sep  5 04:36:29 a7574958f39a syslog-ng[29]: syslog-ng shutting down; version='3.5.6'
Sep  5 04:36:29 a7574958f39a syslog-ng[29]: EOF on control channel, closing connection;
*** Killing all processes...
```

**Comment by lorenzschmid** [comment]
My bad as well: Mounting `/etc/localtime` in the docker container was apparently a bad idea. Removing it resolved the problem.

**Comment by TexasDex** [comment]
Is there any word on how that caused the issue?  This is [causing trouble](https://forum.rockstor.com/t/trying-to-make-a-new-rock-on-for-seafile/5238/13) with integrating Seafile into Rockstor, because Rockstor binds /etc/localtime by default.

**Comment by TexasDex** [comment]
It looks like the issue could be in scripts/create_data_links.sh, which removes and recreates the timezone based on the TIME_ZONE env var:

```sh
if [[ $TIME_ZONE != "" ]]; then
    time_zone=/usr/share/zoneinfo/$TIME_ZONE
    if [[ ! -e $time_zone ]]; then
        echo "invalid time zone"
        exit 1
    else
        ln -snf $time_zone /etc/localtime
        echo "$TIME_ZONE" > /etc/timezone
    fi
fi
```
It doesn't account for the possibility that /etc/localtime is mounted read only; it just tries to create it if TIME_ZONE is empty, even if it already exists.
