### ISSUE TITLE
Crash on recreating container

### ISSUE THREAD

**Issue by stan2014** [haiwen/seafile-docker#145]
When recreating my seafile container i encountered the following error:

> *** Running /etc/my_init.d/01_create_data_links.sh...,
*** Running /etc/my_init.d/10_syslog-ng.init...,
Feb 28 09:25:13 f5e043d92a12 syslog-ng[29]: syslog-ng starting up; version='3.13.2',
*** Running /etc/my_init.d/99_mysql_setup.sh...,
*** Booting runit daemon...,
*** Runit started as PID 39,
*** Running /scripts/start.py...,
Feb 28 09:25:14 f5e043d92a12 cron[47]: (CRON) INFO (pidfile fd = 3),
Feb 28 09:25:14 f5e043d92a12 cron[47]: (CRON) INFO (Running @reboot jobs),
[2019-02-28 09:25:14] Preparing for letsencrypt ...,
[2019-02-28 09:25:14] Found existing cert file /shared/ssl/{REDACTED},
Certificate will not expire,
[2019-02-28 09:25:14] Skip letsencrypt verification since we have a valid certificate,
[2019-02-28 09:25:16] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.,
[02/28/2019 09:25:16][upgrade]: The container was recreated, running minor-upgrade.sh to fix the media symlinks,
[02/28/2019 09:25:16][upgrade]: Running script /opt/seafile/seafile-server-6.3.2/upgrade/minor-upgrade.sh,
Traceback (most recent call last):,
  File "/scripts/start.py", line 86, in <module>,
    main(),
  File "/scripts/start.py", line 58, in main,
    check_upgrade(),
  File "/scripts/upgrade.py", line 96, in check_upgrade,
    fix_media_symlinks(current_version),
  File "/scripts/upgrade.py", line 79, in fix_media_symlinks,
    run_minor_upgrade(current_version),
  File "/scripts/upgrade.py", line 83, in run_minor_upgrade,
    run_script_and_update_version_stamp(minor_upgrade_script, current_version),
  File "/scripts/upgrade.py", line 59, in run_script_and_update_version_stamp,
    replace_file_pattern(script, 'read dummy', ''),
  File "/scripts/utils/__init__.py", line 292, in replace_file_pattern,
    with open(fn, 'r') as fp:,
IOError: [Errno 2] No such file or directory: '/opt/seafile/seafile-server-6.3.2/upgrade/minor-upgrade.sh',
*** /scripts/start.py exited with status 1.,
*** Shutting down runit daemon (PID 39)...,
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...,
Feb 28 09:25:20 f5e043d92a12 syslog-ng[29]: syslog-ng shutting down; version='3.13.2',
*** Killing all processes...,

I used this: https://github.com/haiwen/seafile-docker#lets-encrypt-ssl-certificate to setup the container and used https://github.com/haiwen/seafile-docker#upgrading-seafile-server for upgrading.

The old container was for version 6.3.2 on 2018-08-24 and the new container was pulled on 2019-02-28

**Comment by devsf** [comment]
Hi,
I'm having a similar issue on docker recreating. This is the complete restart log:

>  [2019-03-22 09:00:31] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[03/22/2019 09:00:31][upgrade]: The container was recreated, running minor-upgrade.sh to fix the media symlinks
[03/22/2019 09:00:31][upgrade]: Running script /opt/seafile/seafile-server-6.3.4/upgrade/minor-upgrade.sh

> This script would do the minor upgrade for you.
Press [ENTER] to contiune

> migrating avatars ...
Error: avatars directory "/opt/seafile/seahub-data/avatars" does not exist
Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 58, in main
    check_upgrade()
  File "/scripts/upgrade.py", line 96, in check_upgrade
    fix_media_symlinks(current_version)
  File "/scripts/upgrade.py", line 79, in fix_media_symlinks
    run_minor_upgrade(current_version)
  File "/scripts/upgrade.py", line 83, in run_minor_upgrade
    run_script_and_update_version_stamp(minor_upgrade_script, current_version)
  File "/scripts/upgrade.py", line 60, in run_script_and_update_version_stamp
    call(script)
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.4/upgrade/minor-upgrade.sh' returned non-zero exit status 1
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 25)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Mar 22 09:00:33 seafile-7f98cbf7b5-f6qhz syslog-ng[15]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes... 

It seems that found the /shared folder (Skip running setup-seafile-mysql.py because there is existing seafile-data folder.) but it crashes

**Comment by renfeipeng** [comment]
You should refer to this document：
https://download.seafile.com/published/support/docker/6.3%20upgrade%20to%207.0.md
