### ISSUE TITLE
the user running the script ("root") is not the owner of

### ISSUE THREAD

**Issue by Lowmach1ne** [haiwen/seafile-docker#149]
Hi,

I don't know why but after sometime after using seafile I have this error :
```
`*** Running /etc/my_init.d/01_create_data_links.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Mar 24 17:10:57 a44c24f77bc0 syslog-ng[26]: syslog-ng starting up; version='3.13.2'
*** Running /etc/my_init.d/99_mysql_setup.sh...
*** Booting runit daemon...
*** Runit started as PID 36
*** Running /scripts/start.py...
Mar 24 17:10:58 a44c24f77bc0 cron[44]: (CRON) INFO (pidfile fd = 3)
Mar 24 17:10:58 a44c24f77bc0 cron[44]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
[2019-03-24 17:11:00] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[03/24/2019 17:11:00][upgrade]: The container was recreated, running minor-upgrade.sh to fix the media symlinks
[03/24/2019 17:11:00][upgrade]: Running script /opt/seafile/seafile-server-6.3.4/upgrade/minor-upgrade.sh
-------------------------------------------------------------
This script would do the minor upgrade for you.
Press [ENTER] to contiune
-------------------------------------------------------------
------------------------------
migrating avatars ...
DONE
------------------------------
updating seafile-server-latest symbolic link to /opt/seafile/seafile-server-6.3.4 ...
DONE
------------------------------
Error: the user running the script ("root") is not the owner of "/shared/seafile/seafile-data" folder, you should use the user "UNKNOWN" to run the script.
Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 71, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.4/seafile.sh start' returned non-zero exit status 255
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 36)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Mar 24 17:11:03 a44c24f77bc0 syslog-ng[26]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Running /etc/my_init.d/10_syslog-ng.init...
Mar 24 17:12:05 a44c24f77bc0 syslog-ng[26]: syslog-ng starting up; version='3.13.2'
*** Running /etc/my_init.d/99_mysql_setup.sh...
*** Booting runit daemon...
*** Runit started as PID 36
*** Running /scripts/start.py...
Mar 24 17:12:06 a44c24f77bc0 cron[45]: (CRON) INFO (pidfile fd = 3)
Mar 24 17:12:06 a44c24f77bc0 cron[45]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
[2019-03-24 17:12:08] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.
[03/24/2019 17:12:08][upgrade]: The container was recreated, running minor-upgrade.sh to fix the media symlinks
[03/24/2019 17:12:08][upgrade]: Running script /opt/seafile/seafile-server-6.3.4/upgrade/minor-upgrade.sh
-------------------------------------------------------------
This script would do the minor upgrade for you.
Press [ENTER] to contiune
-------------------------------------------------------------
------------------------------
migrating avatars ...
DONE
------------------------------
updating seafile-server-latest symbolic link to /opt/seafile/seafile-server-6.3.4 ...
DONE
------------------------------
Error: the user running the script ("root") is not the owner of "/shared/seafile/seafile-data" folder, you should use the user "UNKNOWN" to run the script.
Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 71, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.3.4/seafile.sh start' returned non-zero exit status 255
*** /scripts/start.py exited with status 1.
*** Shutting down runit daemon (PID 36)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
Mar 24 17:12:12 a44c24f77bc0 syslog-ng[26]: syslog-ng shutting down; version='3.13.2'
*** Killing all processes...`
```

**Comment by Brutia** [comment]
Hi @Lowmach1ne , I'm facing the same issue. 
Did you find how to solve this?

**Comment by matejdro** [comment]
In case anyone is experiencing the same problem, I solved it by starting `/bin/bash` inside seafile image and running `chmod -R root:root /shared/seafile/seafile-data`

**Comment by ericthomasca** [comment]
> In case anyone is experiencing the same problem, I solved it by starting `/bin/bash` inside seafile image and running `chmod -R root:root /shared/seafile/seafile-data`

The command should be `chown -R root:root /shared/seafile/seafile-data`

**Comment by howtobanana** [comment]
Hi, I have the exact same issue but I'm unable to execute "/bin/bash" and "chown -R root:root /shared/seafile/seafile-data" due to the fact that the docker container on my Unraid server is killing the process in a matter of seconds after starting it.
How am I able to get around this?
