### ISSUE TITLE
7.1.3 ModuleNotFoundError: No module named 'requests_oauthlib'

### ISSUE THREAD

**Issue by MateEke** [haiwen/seafile-docker#212]
I have upgraded to 7.1.3 image (CE) and I get internal server error from seahub.

log:
```
Starting seahub at port 8000 ...
[2020-04-22 09:45:18 +0200] [118] [INFO] Starting gunicorn 20.0.4
[2020-04-22 09:45:18 +0200] [118] [INFO] Listening at: http://127.0.0.1:8000 (118)
[2020-04-22 09:45:18 +0200] [118] [INFO] Using worker: sync
[2020-04-22 09:45:18 +0200] [122] [INFO] Booting worker with pid: 122
[2020-04-22 09:45:18 +0200] [123] [INFO] Booting worker with pid: 123
[2020-04-22 09:45:18 +0200] [124] [INFO] Booting worker with pid: 124
[2020-04-22 09:45:18 +0200] [125] [INFO] Booting worker with pid: 125
[2020-04-22 09:45:18 +0200] [126] [INFO] Booting worker with pid: 126
[2020-04-22 09:45:29 +0200] [123] [ERROR] Error handling request /
Traceback (most recent call last):
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/middleware/locale.py", line 24, in process_request
    i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
    for url_pattern in get_resolver(urlconf).url_patterns:
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/utils/rooturl.py", line 41, in <module>
    url(r'^%s' % settings.SITE_ROOT[1:], include(settings.SITE_ROOT_URLCONF)),
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/urls.py", line 182, in <module>
    url(r'^oauth/', include('seahub.oauth.urls')),
  File "/opt/seafile/seafile-server-7.1.3/seahub/thirdpart/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/oauth/urls.py", line 4, in <module>
    from seahub.oauth.views import oauth_login, oauth_callback
  File "/opt/seafile/seafile-server-7.1.3/seahub/seahub/oauth/views.py", line 20, in <module>
    from requests_oauthlib import OAuth2Session
ModuleNotFoundError: No module named 'requests_oauthlib'

```

**Comment by MateEke** [comment]
Disabling oauth is a temporary solution
