### ISSUE TITLE
mysql does not start on bootstrap

### ISSUE THREAD

**Issue by bebehei** [haiwen/seafile-docker#25]
I'm following the installation of the README.

- Copied boostrap.conf and edited it.
- running `./launcher bootstrap`:

```
[root@bread:/srv/docker/seafile/seafile-docker] master ± ./launcher -v bootstrap
*** Running /etc/my_init.d/99_mysql_setup.sh...
*** Running /etc/my_init.d/create_data_links.sh...
*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 10
*** Running /scripts/bootstrap.py...
[2017-07-04 09:31:27] Generating local Dockerfile ...
[2017-07-04 09:31:27] [debug] waiting for mysql server to be ready
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
[2017-07-04 09:31:29] [debug] mysql server is ready
[2017-07-04 09:31:29] Now running setup-seafile-mysql.py in auto mode.
Checking python on this machine ...
  Checking python module: setuptools ... Done.
  Checking python module: python-imaging ... Done.
  Checking python module: python-mysqldb ... Done.


verifying password of user root ...  
verifying password of user root ...  
Failed to connect to mysql server using user "root" and password "***": Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)                                                     

Traceback (most recent call last):
  File "/scripts/bootstrap.py", line 196, in <module>
    main()
  File "/scripts/bootstrap.py", line 189, in main
    init_seafile_server()
  File "/scripts/bootstrap.py", line 141, in init_seafile_server
    call('{} auto -n seafile'.format(setup_script), env=env)
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.0.9/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 255
*** /scripts/bootstrap.py exited with status 1.
*** Shutting down runit daemon (PID 10)...
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111 "Connection refused")'
Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
*** Killing all processes...
```

Why does MySQL not start?

I'm running this on basic ArchLinux System. Running with docker 17.05.

**Comment by goarano** [comment]
I have the same issue.

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
