### ISSUE TITLE
Seafile docker MC error

### ISSUE THREAD

**Issue by zsamiatt** [haiwen/seafile-docker#284]
Hello I upgraded to latest sefile docker. But the new docker have error. 

*** Running /etc/my_init.d/01_create_data_links.sh...

*** Booting runit daemon...

*** Runit started as PID 25

*** Running /scripts/enterpoint.sh...

2022-02-17 05:25:25 Nginx ready 

2022-02-17 05:25:25 This is a idle script (infinite loop) to keep container running. 

[02/17/2022 05:25:27][upgrade]: The container was recreated, start fix the media symlinks

mv: cannot stat '/opt/seafile/seafile-server-8.0.7/seahub/media/avatars/*': No such file or directory

[2022-02-17 05:25:27] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.

Traceback (most recent call last):

  File "/scripts/start.py", line 86, in <module>

    main()

  File "/scripts/start.py", line 58, in main

    check_upgrade()

  File "/scripts/upgrade.py", line 95, in check_upgrade

    fix_media_symlinks()

  File "/scripts/upgrade.py", line 79, in fix_media_symlinks

    call('mv -n %s/* %s' % (avatars_dir, dst_avatars_dir))

  File "/scripts/utils.py", line 70, in call

    return subprocess.check_call(*a, **kw)

  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'mv -n /opt/seafile/seafile-server-8.0.7/seahub/media/avatars/* /shared/seafile/seahub-data/avatars' returned non-zero exit status 1.

**Comment by zsamiatt** [comment]
any idea?

**Comment by zsamiatt** [comment]
I find the error. In docker file this path not valid:  /opt/seafile/seafile-server-8.0.7/seahub/media/avatars/

The new docker file valid path:
/opt/seafile/seafile-server-9.0.4/seahub/media/avatars/

How can rewrite the path in database?

**Comment by fatih-atasever** [comment]
I had the same error and updating ENV variable `SEAFILE_VERSION` to the correct version fixed it for me.
