### ISSUE TITLE
The unauthenticated git protocol on port 9418 is no longer supported

### ISSUE THREAD

**Issue by hmes98318** [haiwen/seafile-docker#291]
This problem happened when i restarted the container, is there any way to fix it?
```
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 25
*** Running /scripts/enterpoint.sh...
2022-04-10 07:11:21 Nginx ready 
2022-04-10 07:11:21 This is a idle script (infinite loop) to keep container running. 
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/seafile.nginx.conf:20
Certificate will expire
nginx: [warn] the "ssl" directive is deprecated, use the "listen ... ssl" directive instead in /etc/nginx/sites-enabled/seafile.nginx.conf:20
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
[2022-04-10 07:11:21] Preparing for letsencrypt ...
[2022-04-10 07:11:21] Found existing cert file /shared/ssl/domain.com.crt
[2022-04-10 07:11:21] Starting letsencrypt verification
Traceback (most recent call last):
  File "/scripts/start.py", line 86, in <module>
    main()
  File "/scripts/start.py", line 51, in main
    init_letsencrypt()
  File "/scripts/bootstrap.py", line 71, in init_letsencrypt
    call('/scripts/ssl.sh {0} {1}'.format(ssl_dir, domain))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/scripts/ssl.sh /shared/ssl domain.com' returned non-zero exit status 1.
```

**Comment by vladkar** [comment]
https://forum.seafile.com/t/docker-ce-installation-fails-to-renew-certificate/16177

Probably these changes can be applied via simple pull request

**Comment by hmes98318** [comment]
Thanks for your helping! : )
