### ISSUE TITLE
Failed to prepare seahub avatars dir

### ISSUE THREAD

**Issue by joydashy** [haiwen/seafile-docker#334]
Running a fresh install using Docker Compose I run into this issue:

```
seafile      | Error: Failed to prepare seahub avatars dir: [Errno 22] Invalid argument: 'groups'
seafile      | [2023-03-16 15:27:57] Now running setup-seafile-mysql.py in auto mode.
seafile      | Traceback (most recent call last):
seafile      |   File "/scripts/start.py", line 92, in <module>
seafile      |     main()
seafile      |   File "/scripts/start.py", line 56, in main
seafile      |     init_seafile_server()
seafile      |   File "/scripts/bootstrap.py", line 158, in init_seafile_server
seafile      |     call('{} auto -n seafile'.format(setup_script), env=env)
seafile      |   File "/scripts/utils.py", line 70, in call
seafile      |     return subprocess.check_call(*a, **kw)
seafile      |   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
seafile      |     raise CalledProcessError(retcode, cmd)
seafile      | subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-9.0.10/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 1.
```

**Comment by norbertterzin** [comment]
I have the same issue. I checked the filesystem and it looks like the 'groups' in avatars folder is corrupt. The rmdir and other commands cannot delete this folder.
I removed the avatar rm/mv/ln handling from the /scripts/upgrade.py
