### ISSUE TITLE
Casting port to int breaks in bootstrap.py

### ISSUE THREAD

**Issue by ragekit** [haiwen/seafile-docker#373]
Hey all !
In reference, forum post : https://forum.seafile.com/t/error-when-using-docker-in-bootstrap-py-typeerror-expected-str-bytes-or-os-pathlike-object-not-int/19248

Cating to int the port number in  : https://github.com/haiwen/seafile-docker/blob/3d92b4dad60525f88b039c6c425dc0fa45d2a90d/scripts/scripts_11.0/bootstrap.py#L149
is breaking install on my raspberry pi 4, works fine if I edit to use a string instead of an int.
I think @SkywalkerSpace made this change according to git blame.

callstack :
```
 | Traceback (most recent call last):
seafile            |   File "/scripts/start.py", line 95, in <module>
seafile            | waiting for mysql server to be ready: %s (2003, "Can't connect to MySQL server on 'db' ([Errno 111] Connection refused)")
seafile            |     main()
seafile            |   File "/scripts/start.py", line 59, in main
seafile            |     init_seafile_server()
seafile            |   File "/scripts/bootstrap.py", line 166, in init_seafile_server
seafile            |     call('{} auto -n seafile'.format(setup_script), env=env)
seafile            |   File "/scripts/utils.py", line 70, in call
seafile            |     return subprocess.check_call(*a, **kw)
seafile            |   File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
seafile            |     retcode = call(*popenargs, **kwargs)
seafile            |   File "/usr/lib/python3.10/subprocess.py", line 345, in call
seafile            |     with Popen(*popenargs, **kwargs) as p:
seafile            |   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
seafile            |     self._execute_child(args, executable, preexec_fn, close_fds,
seafile            |   File "/usr/lib/python3.10/subprocess.py", line 1783, in _execute_child
seafile            |     env_list.append(k + b'=' + os.fsencode(v))
seafile            |   File "/usr/lib/python3.10/os.py", line 811, in fsencode
seafile            |     filename = fspath(filename)  # Does type-checking of `filename`.
seafile            | TypeError: expected str, bytes or os.PathLike object, not int
```

**Comment by ragekit** [comment]
just to confirm docker image version [11.0.4](https://hub.docker.com/layers/seafileltd/seafile-mc/11.0.4/images/sha256-708f441c25d6c9117a763d02f39e8ac1cc075d129fe1fa7702165655526198d5?context=explore)

works perfectly

**Comment by Gabrielx117** [comment]
https://forum.seafile.com/t/error-when-using-docker-in-bootstrap-py-typeerror-expected-str-bytes-or-os-pathlike-object-not-int/19248
改成 'MYSQL_PORT':  get_conf('DB_PORT', '3306'),

**Comment by ragekit** [comment]
I know this is me in the forum !
