### ISSUE TITLE
docker 的12社区版无法运行

### ISSUE THREAD

**Issue by Omoinemie** [haiwen/seafile-docker#422]
我照着说明文档用纯净的系统安装的，运行seafile容器报错
系统版本：Ubuntu 22.04
镜像版本：seafileltd/seafile-mc:12.0-latest

`*** Shutting down /scripts/enterpoint.sh (PID 22)...
*** Shutting down runit daemon (PID 21)...
*** Running /etc/my_init.post_shutdown.d/10_syslog-ng.shutdown...
*** Init system aborted.
*** Killing all processes...
*** Running /etc/my_init.d/01_create_data_links.sh...
*** Booting runit daemon...
*** Runit started as PID 21
*** Running /scripts/enterpoint.sh...
2024-12-09 16:27:07 Nginx ready 
2024-12-09 16:27:07 This is an idle script (infinite loop) to keep container running. 
[2024-12-09 16:27:07] Skip running setup-seafile-mysql.py because there is existing seafile-data folder.

Error: .env file not found.
Please follow the upgrade manual to set the .env file.

Traceback (most recent call last):
  File "/scripts/start.py", line 94, in <module>
    main()
  File "/scripts/start.py", line 79, in main
    call('{} start'.format(get_script('seafile.sh')))
  File "/scripts/utils.py", line 70, in call
    return subprocess.check_call(*a, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-12.0.4/seafile.sh start' returned non-zero exit status 255.`

**Comment by Rohurd** [comment]
I had the same error. I looked into the seafile.sh script, and it seems the .env file now also needs to be in the conf folder (/opt/seafile/conf within the container).

**Comment by freeplant** [comment]
Please try again with the latest version and make sure JWT_PRIVATE_KEY is specified .env for docker. Otherwise, the seafile.sh script will looking for .env file in `/opt/seafile/conf`.
