### ISSUE TITLE
Error: Failed to prepare seahub avatars dir: [Errno 39] Directory not empty:

### ISSUE THREAD

**Issue by cwester** [haiwen/seafile-docker#9]
Seems I found a bug with this. When running ./launcher bootstrap I get the following error:

```
----------------------------------------
Now creating seahub database tables ...

----------------------------------------

Error: Failed to prepare seahub avatars dir: [Errno 39] Directory not empty: '/opt/seafile/seafile-server-6.0.7/seahub/media/avatars/groups'
Traceback (most recent call last):
  File "/scripts/bootstrap.py", line 196, in <module>
    main()
  File "/scripts/bootstrap.py", line 189, in main
    init_seafile_server()
  File "/scripts/bootstrap.py", line 141, in init_seafile_server
    call('{} auto -n seafile'.format(setup_script), env=env)
  File "/scripts/utils/__init__.py", line 68, in call
    return subprocess.check_call(*a, **kw)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/seafile/seafile-server-6.0.7/setup-seafile-mysql.sh auto -n seafile' returned non-zero exit status 1
```

**Comment by lintghi** [comment]
me too

**Comment by jasoncook** [comment]
Yup. Same here.

**Comment by sholl** [comment]
any idee how to solve this issue?

**Comment by DerTFL** [comment]
I have this problem too on Centos 7.4

**Comment by freeplant** [comment]
Please try the latest version. `launcher` is no longer used.
